/**
 * Configure generated API client and re-export SDK + types.
 * The actual client is auto-generated by @hey-api/openapi-ts from openapi.json.
 * Run: npm run generate:api (uses local openapi.json) or npm run generate:api:live (uses running API).
 */
import { client } from "./api/client.gen";

const baseUrl =
  (typeof window !== "undefined"
    ? process.env.NEXT_PUBLIC_API_URL
    : process.env.NEXT_PUBLIC_API_URL) || "http://localhost:3000";

client.setConfig({ baseUrl: baseUrl as `${string}://${string}` });

export {
  createAttribute,
  createBeverage,
  createCategory,
  createQuestion,
  createType,
  deleteQuestion,
  findAllAttributes,
  findAllQuestions,
  findAttributesByCategory,
  findQuestionsByCategory,
  findQuestionsByType,
  getAllBeverages,
  getAllCategories,
  getAllReviews,
  getAllTypes,
  getAttributeById,
  getBeverageById,
  getCategoryById,
  getQuestionById,
  getReviewById,
  getTypeById,
  type Options,
} from "./api/sdk.gen";

export type {
  AttributeDefinition,
  Beverage,
  BeverageCategory,
  BeverageType,
  CreateAttributeDefinitionDto,
  CreateBeverageDto,
  CreateBeverageTypeDto,
  CreateCategoryDto,
  CreateQuestionDto,
  Question,
  Review,
} from "./api/types.gen";
