// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateAttributeData, CreateAttributeResponses, CreateBeverageData, CreateBeverageResponses, CreateCategoryData, CreateCategoryResponses, CreateQuestionData, CreateQuestionResponses, CreateTypeData, CreateTypeResponses, DeleteQuestionData, DeleteQuestionErrors, DeleteQuestionResponses, FindAllAttributesData, FindAllAttributesResponses, FindAllQuestionsData, FindAllQuestionsResponses, FindAttributesByCategoryData, FindAttributesByCategoryResponses, FindQuestionsByCategoryData, FindQuestionsByCategoryResponses, FindQuestionsByTypeData, FindQuestionsByTypeResponses, GetAllBeveragesData, GetAllBeveragesResponses, GetAllCategoriesData, GetAllCategoriesResponses, GetAllReviewsData, GetAllReviewsResponses, GetAllTypesData, GetAllTypesResponses, GetAttributeByIdData, GetAttributeByIdErrors, GetAttributeByIdResponses, GetBeverageByIdData, GetBeverageByIdErrors, GetBeverageByIdResponses, GetCategoryByIdData, GetCategoryByIdResponses, GetQuestionByIdData, GetQuestionByIdErrors, GetQuestionByIdResponses, GetReviewByIdData, GetReviewByIdErrors, GetReviewByIdResponses, GetTypeByIdData, GetTypeByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getAllCategories = <ThrowOnError extends boolean = false>(options?: Options<GetAllCategoriesData, ThrowOnError>) => (options?.client ?? client).get<GetAllCategoriesResponses, unknown, ThrowOnError>({ url: '/api/admin/beverage-categories', ...options });

export const createCategory = <ThrowOnError extends boolean = false>(options?: Options<CreateCategoryData, ThrowOnError>) => (options?.client ?? client).post<CreateCategoryResponses, unknown, ThrowOnError>({
    url: '/api/admin/beverage-categories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getCategoryById = <ThrowOnError extends boolean = false>(options: Options<GetCategoryByIdData, ThrowOnError>) => (options.client ?? client).get<GetCategoryByIdResponses, unknown, ThrowOnError>({ url: '/api/admin/beverage-categories/{id}', ...options });

export const getAllTypes = <ThrowOnError extends boolean = false>(options?: Options<GetAllTypesData, ThrowOnError>) => (options?.client ?? client).get<GetAllTypesResponses, unknown, ThrowOnError>({ url: '/api/admin/beverage-types', ...options });

export const createType = <ThrowOnError extends boolean = false>(options?: Options<CreateTypeData, ThrowOnError>) => (options?.client ?? client).post<CreateTypeResponses, unknown, ThrowOnError>({
    url: '/api/admin/beverage-types',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getTypeById = <ThrowOnError extends boolean = false>(options: Options<GetTypeByIdData, ThrowOnError>) => (options.client ?? client).get<GetTypeByIdResponses, unknown, ThrowOnError>({ url: '/api/admin/beverage-types/{id}', ...options });

export const getAllBeverages = <ThrowOnError extends boolean = false>(options?: Options<GetAllBeveragesData, ThrowOnError>) => (options?.client ?? client).get<GetAllBeveragesResponses, unknown, ThrowOnError>({ url: '/api/admin/beverages', ...options });

export const createBeverage = <ThrowOnError extends boolean = false>(options?: Options<CreateBeverageData, ThrowOnError>) => (options?.client ?? client).post<CreateBeverageResponses, unknown, ThrowOnError>({
    url: '/api/admin/beverages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getBeverageById = <ThrowOnError extends boolean = false>(options: Options<GetBeverageByIdData, ThrowOnError>) => (options.client ?? client).get<GetBeverageByIdResponses, GetBeverageByIdErrors, ThrowOnError>({ url: '/api/admin/beverages/{id}', ...options });

export const findAllAttributes = <ThrowOnError extends boolean = false>(options?: Options<FindAllAttributesData, ThrowOnError>) => (options?.client ?? client).get<FindAllAttributesResponses, unknown, ThrowOnError>({ url: '/api/admin/attributes', ...options });

export const createAttribute = <ThrowOnError extends boolean = false>(options?: Options<CreateAttributeData, ThrowOnError>) => (options?.client ?? client).post<CreateAttributeResponses, unknown, ThrowOnError>({
    url: '/api/admin/attributes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const findAttributesByCategory = <ThrowOnError extends boolean = false>(options: Options<FindAttributesByCategoryData, ThrowOnError>) => (options.client ?? client).get<FindAttributesByCategoryResponses, unknown, ThrowOnError>({ url: '/api/admin/attributes/category/{categoryId}', ...options });

export const getAttributeById = <ThrowOnError extends boolean = false>(options: Options<GetAttributeByIdData, ThrowOnError>) => (options.client ?? client).get<GetAttributeByIdResponses, GetAttributeByIdErrors, ThrowOnError>({ url: '/api/admin/attributes/{id}', ...options });

export const getAllReviews = <ThrowOnError extends boolean = false>(options?: Options<GetAllReviewsData, ThrowOnError>) => (options?.client ?? client).get<GetAllReviewsResponses, unknown, ThrowOnError>({ url: '/api/admin/reviews', ...options });

export const getReviewById = <ThrowOnError extends boolean = false>(options: Options<GetReviewByIdData, ThrowOnError>) => (options.client ?? client).get<GetReviewByIdResponses, GetReviewByIdErrors, ThrowOnError>({ url: '/api/admin/reviews/{id}', ...options });

export const findAllQuestions = <ThrowOnError extends boolean = false>(options?: Options<FindAllQuestionsData, ThrowOnError>) => (options?.client ?? client).get<FindAllQuestionsResponses, unknown, ThrowOnError>({ url: '/api/admin/questions', ...options });

export const createQuestion = <ThrowOnError extends boolean = false>(options?: Options<CreateQuestionData, ThrowOnError>) => (options?.client ?? client).post<CreateQuestionResponses, unknown, ThrowOnError>({
    url: '/api/admin/questions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const findQuestionsByCategory = <ThrowOnError extends boolean = false>(options: Options<FindQuestionsByCategoryData, ThrowOnError>) => (options.client ?? client).get<FindQuestionsByCategoryResponses, unknown, ThrowOnError>({ url: '/api/admin/questions/category/{categoryId}', ...options });

export const findQuestionsByType = <ThrowOnError extends boolean = false>(options: Options<FindQuestionsByTypeData, ThrowOnError>) => (options.client ?? client).get<FindQuestionsByTypeResponses, unknown, ThrowOnError>({ url: '/api/admin/questions/type/{typeId}', ...options });

export const deleteQuestion = <ThrowOnError extends boolean = false>(options: Options<DeleteQuestionData, ThrowOnError>) => (options.client ?? client).delete<DeleteQuestionResponses, DeleteQuestionErrors, ThrowOnError>({ url: '/api/admin/questions/{id}', ...options });

export const getQuestionById = <ThrowOnError extends boolean = false>(options: Options<GetQuestionByIdData, ThrowOnError>) => (options.client ?? client).get<GetQuestionByIdResponses, GetQuestionByIdErrors, ThrowOnError>({ url: '/api/admin/questions/{id}', ...options });
