// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type User = {
    /**
     * User ID
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Hashed password (admin only)
     */
    passwordHash: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
};

export type CreateImageDto = {
    /**
     * URL to the image
     */
    url: string;
    /**
     * Type of image (e.g. thumbnail, large, profile, icon)
     */
    type: 'THUMBNAIL' | 'LARGE' | 'PROFILE' | 'ICON';
    /**
     * Bredde (px)
     */
    width?: number;
    /**
     * Højde (px)
     */
    height?: number;
};

export type CreateUserDto = {
    /**
     * Unique username for the user
     */
    username: string;
    /**
     * Email address of the user
     */
    email: string;
    /**
     * Hashed password for the user
     */
    passwordHash: string;
    /**
     * List of images (e.g. profile picture)
     */
    images?: Array<CreateImageDto>;
};

export type PresignSlotDto = {
    /**
     * Image type (e.g. thumbnail, large, profile, icon)
     */
    type: 'THUMBNAIL' | 'LARGE' | 'PROFILE' | 'ICON';
    /**
     * Bredde (px) – bruges i key som .../id/widthxheight. Default per type hvis udeladt.
     */
    width?: number;
    /**
     * Højde (px) – bruges i key som .../id/widthxheight. Default per type hvis udeladt.
     */
    height?: number;
};

export type PresignUploadDto = {
    /**
     * List of image slots – one entry per file you will upload
     */
    uploads: Array<PresignSlotDto>;
    /**
     * Presigned URL expiry in seconds (default: 900)
     */
    expiresInSeconds?: number;
};

export type Brand = {
    /**
     * Brand ID
     */
    id: string;
    /**
     * Brand name
     */
    name: string;
    /**
     * Brand description
     */
    description?: {
        [key: string]: unknown;
    };
    /**
     * Whether the brand is active
     */
    active: boolean;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * IDs of categories this brand is allowed in (empty = all)
     */
    categoryIds: Array<string>;
};

export type Image = {
    /**
     * Image ID
     */
    id: string;
    /**
     * Image URL, or for type ICON the icon itself (e.g. an emoji character like 🍷) – not a link in that case.
     */
    url: string;
    /**
     * Image type
     */
    type: 'THUMBNAIL' | 'LARGE' | 'PROFILE' | 'ICON';
    /**
     * Width in pixels
     */
    width?: {
        [key: string]: unknown;
    };
    /**
     * Height in pixels
     */
    height?: {
        [key: string]: unknown;
    };
};

export type Beverage = {
    /**
     * Beverage ID
     */
    id: string;
    /**
     * Beverage type ID
     */
    beverageTypeId: string;
    /**
     * Brand ID
     */
    brandId: string;
    /**
     * Beverage name
     */
    name: string;
    /**
     * Country code
     */
    country: string;
    /**
     * Additional metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * Average rating
     */
    averageRating: number;
    /**
     * Number of reviews
     */
    reviewCount: number;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Brand (when included)
     */
    brand?: Brand;
    /**
     * Images (when included)
     */
    images?: Array<Image>;
};

export type CreateBeverageDto = {
    /**
     * ID of the beverage type
     */
    beverageTypeId: string;
    /**
     * ID of the brand
     */
    brandId: string;
    /**
     * Name of the beverage
     */
    name: string;
    /**
     * Country code where the beverage is from
     */
    country?: string;
    /**
     * Additional metadata as JSON object
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * List of images (e.g. thumbnail, large)
     */
    images?: Array<CreateImageDto>;
};

export type UpdateBeverageDto = {
    /**
     * ID of the beverage type
     */
    beverageTypeId?: string;
    /**
     * ID of the brand
     */
    brandId?: string;
    /**
     * Name of the beverage
     */
    name?: string;
    /**
     * Country code where the beverage is from
     */
    country?: string;
    /**
     * Additional metadata as JSON object
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * List of images (e.g. thumbnail, large)
     */
    images?: Array<CreateImageDto>;
};

export type Review = {
    /**
     * Review ID
     */
    id: string;
    /**
     * User ID
     */
    userId: string;
    /**
     * Beverage ID
     */
    beverageId: string;
    /**
     * Rating (0–5)
     */
    rating: number;
    /**
     * Review title
     */
    title?: {
        [key: string]: unknown;
    };
    /**
     * Review description
     */
    description?: {
        [key: string]: unknown;
    };
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
};

export type CreateReviewDto = {
    /**
     * ID of the user creating the review
     */
    userId: string;
    /**
     * ID of the beverage being reviewed
     */
    beverageId: string;
    /**
     * Rating from 0 to 5
     */
    rating: number;
    /**
     * Title of the review
     */
    title?: string;
    /**
     * Detailed review description
     */
    description?: string;
};

export type UpdateReviewDto = {
    /**
     * ID of the user creating the review
     */
    userId?: string;
    /**
     * ID of the beverage being reviewed
     */
    beverageId?: string;
    /**
     * Rating from 0 to 5
     */
    rating?: number;
    /**
     * Title of the review
     */
    title?: string;
    /**
     * Detailed review description
     */
    description?: string;
};

export type BeverageCategory = {
    /**
     * Category ID
     */
    id: string;
    /**
     * Category name
     */
    name: string;
    /**
     * Category description
     */
    description?: {
        [key: string]: unknown;
    };
    /**
     * Category images (e.g. icon)
     */
    images?: Array<Image>;
};

export type CreateCategoryDto = {
    /**
     * The name of the beverage category
     */
    name: string;
    /**
     * Icon – tom eller præcis én emoji
     */
    icon?: string;
    /**
     * The description of the beverage category
     */
    description: string;
    /**
     * List of images (e.g. icon)
     */
    images?: Array<CreateImageDto>;
};

export type UpdateCategoryDto = {
    /**
     * The name of the beverage category
     */
    name?: string;
    /**
     * Icon – tom eller præcis én emoji
     */
    icon?: string;
    /**
     * The description of the beverage category
     */
    description?: string;
    /**
     * List of images (e.g. icon)
     */
    images?: Array<CreateImageDto>;
};

export type BeverageType = {
    /**
     * Beverage type ID
     */
    id: string;
    /**
     * Category ID
     */
    categoryId: string;
    /**
     * Type name
     */
    name: string;
    /**
     * Type description
     */
    description?: {
        [key: string]: unknown;
    };
    /**
     * Whether the type is active
     */
    active: boolean;
    /**
     * Creation timestamp
     */
    createdAt: string;
};

export type CreateBeverageTypeDto = {
    /**
     * Name of the beverage type
     */
    name: string;
    /**
     * ID of the beverage category this type belongs to
     */
    categoryId: string;
    /**
     * Description of the beverage type
     */
    description?: string;
    /**
     * Whether the beverage type is active
     */
    active?: boolean;
};

export type UpdateBeverageTypeDto = {
    /**
     * Name of the beverage type
     */
    name?: string;
    /**
     * ID of the beverage category this type belongs to
     */
    categoryId?: string;
    /**
     * Description of the beverage type
     */
    description?: string;
    /**
     * Whether the beverage type is active
     */
    active?: boolean;
};

export type CreateBrandDto = {
    /**
     * Name of the brand
     */
    name: string;
    /**
     * Description of the brand
     */
    description?: string;
    /**
     * Whether the brand is active
     */
    active?: boolean;
    /**
     * IDs of categories this brand is allowed in (empty = all)
     */
    categoryIds?: Array<string>;
};

export type UpdateBrandDto = {
    /**
     * Name of the brand
     */
    name?: string;
    /**
     * Description of the brand
     */
    description?: string;
    /**
     * Whether the brand is active
     */
    active?: boolean;
    /**
     * IDs of categories this brand is allowed in (empty = all)
     */
    categoryIds?: Array<string>;
};

export type CreateAttributeDefinitionDto = {
    /**
     * IDs of beverage categories this attribute applies to
     */
    categoryIds: Array<string>;
    /**
     * IDs of beverage types (optional; empty = applies to all types in the selected categories)
     */
    typeIds?: Array<string>;
    /**
     * Unique key identifier for the attribute
     */
    attributeKey: string;
    /**
     * Display name for the attribute
     */
    displayName: string;
    /**
     * Data type of the attribute value
     */
    dataType: 'string' | 'number' | 'boolean';
    /**
     * Whether this attribute can be used for filtering
     */
    filterable?: boolean;
    /**
     * Whether this attribute is required
     */
    required?: boolean;
};

export type AttributeDefinition = {
    /**
     * Attribute definition ID
     */
    id: string;
    /**
     * Category IDs this attribute applies to
     */
    categoryIds: Array<string>;
    /**
     * Type IDs (optional; empty = all types in the categories)
     */
    typeIds?: Array<string>;
    /**
     * Attribute key
     */
    attributeKey: string;
    /**
     * Display name
     */
    displayName: string;
    /**
     * Data type
     */
    dataType: 'string' | 'number' | 'boolean';
    /**
     * Whether attribute is filterable
     */
    filterable: boolean;
    /**
     * Whether attribute is required
     */
    required: boolean;
    /**
     * Validation rules (JSON)
     */
    validationRules?: {
        [key: string]: unknown;
    };
    /**
     * Options (JSON)
     */
    options?: {
        [key: string]: unknown;
    };
    /**
     * Sort order
     */
    sortOrder?: {
        [key: string]: unknown;
    };
};

export type UpdateAttributeDefinitionDto = {
    /**
     * IDs of beverage categories this attribute applies to
     */
    categoryIds?: Array<string>;
    /**
     * IDs of beverage types (optional; empty = applies to all types in the selected categories)
     */
    typeIds?: Array<string>;
    /**
     * Unique key identifier for the attribute
     */
    attributeKey?: string;
    /**
     * Display name for the attribute
     */
    displayName?: string;
    /**
     * Data type of the attribute value
     */
    dataType?: 'string' | 'number' | 'boolean';
    /**
     * Whether this attribute can be used for filtering
     */
    filterable?: boolean;
    /**
     * Whether this attribute is required
     */
    required?: boolean;
};

export type CreateBeverageAttributeValueDto = {
    /**
     * ID of the beverage
     */
    beverageId: string;
    /**
     * ID of the attribute definition
     */
    attributeId: string;
    /**
     * String value (use if attribute dataType is string)
     */
    valueString?: string;
    /**
     * Number value (use if attribute dataType is number)
     */
    valueNumber?: number;
    /**
     * Boolean value (use if attribute dataType is boolean)
     */
    valueBoolean?: boolean;
};

export type BeverageAttributeValue = {
    /**
     * Attribute value ID
     */
    id: string;
    /**
     * Beverage ID
     */
    beverageId: string;
    /**
     * Attribute definition ID
     */
    attributeId: string;
    /**
     * String value
     */
    valueString?: {
        [key: string]: unknown;
    };
    /**
     * Number value
     */
    valueNumber?: {
        [key: string]: unknown;
    };
    /**
     * Boolean value
     */
    valueBoolean?: {
        [key: string]: unknown;
    };
};

export type UpdateBeverageAttributeValueDto = {
    /**
     * ID of the beverage
     */
    beverageId?: string;
    /**
     * ID of the attribute definition
     */
    attributeId?: string;
    /**
     * String value (use if attribute dataType is string)
     */
    valueString?: string;
    /**
     * Number value (use if attribute dataType is number)
     */
    valueNumber?: number;
    /**
     * Boolean value (use if attribute dataType is boolean)
     */
    valueBoolean?: boolean;
};

export type CreateQuestionDto = {
    /**
     * ID of the beverage category
     */
    categoryId: string;
    /**
     * ID of the beverage type (optional – question applies to all types in category if omitted)
     */
    typeId?: string;
    /**
     * Question text
     */
    questionText: string;
    /**
     * Answer type
     */
    answerType: 'text' | 'number' | 'select' | 'rating';
    /**
     * Options for select-type (e.g. array of choices)
     */
    options?: {
        [key: string]: unknown;
    };
    /**
     * Sort order (lower = first)
     */
    sortOrder?: number;
    /**
     * Whether the question is required
     */
    required?: boolean;
};

export type Question = {
    /**
     * Question ID
     */
    id: string;
    /**
     * Beverage category ID
     */
    categoryId: string;
    /**
     * Beverage type ID (optional)
     */
    typeId?: {
        [key: string]: unknown;
    };
    /**
     * Question text
     */
    questionText: string;
    /**
     * Answer type
     */
    answerType: 'text' | 'number' | 'select' | 'rating';
    /**
     * Options for select-type (e.g. array of choices)
     */
    options?: {
        [key: string]: unknown;
    };
    /**
     * Sort order (lower = first)
     */
    sortOrder?: {
        [key: string]: unknown;
    };
    /**
     * Whether the question is required
     */
    required: boolean;
};

export type UpdateQuestionDto = {
    /**
     * ID of the beverage category
     */
    categoryId?: string;
    /**
     * ID of the beverage type (optional – question applies to all types in category if omitted)
     */
    typeId?: string;
    /**
     * Question text
     */
    questionText?: string;
    /**
     * Answer type
     */
    answerType?: 'text' | 'number' | 'select' | 'rating';
    /**
     * Options for select-type (e.g. array of choices)
     */
    options?: {
        [key: string]: unknown;
    };
    /**
     * Sort order (lower = first)
     */
    sortOrder?: number;
    /**
     * Whether the question is required
     */
    required?: boolean;
};

export type UserControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/users';
};

export type UserControllerGetAllResponses = {
    /**
     * List of users retrieved successfully
     */
    200: Array<User>;
};

export type UserControllerGetAllResponse = UserControllerGetAllResponses[keyof UserControllerGetAllResponses];

export type UserControllerCreateData = {
    /**
     * User data to create
     */
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/api/admin/users';
};

export type UserControllerCreateErrors = {
    /**
     * Invalid input data
     */
    400: unknown;
};

export type UserControllerCreateResponses = {
    /**
     * User created successfully
     */
    201: User;
};

export type UserControllerCreateResponse = UserControllerCreateResponses[keyof UserControllerCreateResponses];

export type UploadControllerPresignData = {
    body: PresignUploadDto;
    headers?: {
        /**
         * Valgfri bucket (fx til test) – opretter ny bucket med public policy hvis den ikke findes
         */
        'X-Test-Bucket'?: string;
    };
    path: {
        /**
         * Upload-type – backend vælger bucket og mappesti
         */
        context: 'beverage-images' | 'user-profile' | 'category-icons';
    };
    query?: never;
    url: '/api/admin/upload/presign/{context}';
};

export type UploadControllerPresignErrors = {
    /**
     * Ugyldig request eller bucket findes ikke
     */
    400: unknown;
};

export type UploadControllerPresignResponses = {
    /**
     * Presigned URLs oprettet
     */
    201: {
        uploads?: Array<{
            /**
             * PUT fil til denne URL
             */
            uploadUrl?: string;
            /**
             * Brug denne URL i images[] ved oprettelse
             */
            url?: string;
            key?: string;
            type?: 'THUMBNAIL' | 'LARGE' | 'PROFILE' | 'ICON';
            /**
             * Bredde (px) – brug ved oprettelse
             */
            width?: number;
            /**
             * Højde (px) – brug ved oprettelse
             */
            height?: number;
            bucket?: string;
        }>;
    };
};

export type UploadControllerPresignResponse = UploadControllerPresignResponses[keyof UploadControllerPresignResponses];

export type UploadControllerCleanupExpiredPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/upload/cleanup-expired-pending';
};

export type UploadControllerCleanupExpiredPendingResponses = {
    /**
     * Cleanup kørt
     */
    200: {
        ok?: boolean;
        deleted?: number;
    };
};

export type UploadControllerCleanupExpiredPendingResponse = UploadControllerCleanupExpiredPendingResponses[keyof UploadControllerCleanupExpiredPendingResponses];

export type UploadControllerGetCronJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/upload/cron-jobs';
};

export type UploadControllerGetCronJobsResponses = {
    /**
     * Liste over cron-jobs
     */
    200: {
        jobs?: Array<{
            id?: string;
            name?: string;
            /**
             * Cron-udtryk (min time dag måned ugedag)
             */
            schedule?: string;
            description?: string;
            /**
             * Om jobbet kører (evt. betinget af env)
             */
            enabled?: boolean;
        }>;
    };
};

export type UploadControllerGetCronJobsResponse = UploadControllerGetCronJobsResponses[keyof UploadControllerGetCronJobsResponses];

export type UploadControllerCleanupEmptyBucketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/upload/cleanup-empty-buckets';
};

export type UploadControllerCleanupEmptyBucketsResponses = {
    /**
     * Cleanup kørt med rapport
     */
    200: unknown;
};

export type BeverageAdminControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/beverages';
};

export type BeverageAdminControllerGetAllResponses = {
    /**
     * List of beverages
     */
    200: Array<Beverage>;
};

export type BeverageAdminControllerGetAllResponse = BeverageAdminControllerGetAllResponses[keyof BeverageAdminControllerGetAllResponses];

export type BeverageAdminControllerCreateData = {
    body: CreateBeverageDto;
    path?: never;
    query?: never;
    url: '/api/admin/beverages';
};

export type BeverageAdminControllerCreateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type BeverageAdminControllerCreateResponses = {
    /**
     * Beverage created
     */
    201: Beverage;
};

export type BeverageAdminControllerCreateResponse = BeverageAdminControllerCreateResponses[keyof BeverageAdminControllerCreateResponses];

export type BeverageAdminControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Beverage ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverages/{id}';
};

export type BeverageAdminControllerRemoveErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageAdminControllerRemoveResponses = {
    /**
     * Beverage deleted
     */
    200: {
        deleted?: boolean;
    };
};

export type BeverageAdminControllerRemoveResponse = BeverageAdminControllerRemoveResponses[keyof BeverageAdminControllerRemoveResponses];

export type BeverageAdminControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Beverage ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverages/{id}';
};

export type BeverageAdminControllerGetByIdErrors = {
    /**
     * Beverage not found
     */
    404: unknown;
};

export type BeverageAdminControllerGetByIdResponses = {
    /**
     * Beverage found
     */
    200: Beverage;
};

export type BeverageAdminControllerGetByIdResponse = BeverageAdminControllerGetByIdResponses[keyof BeverageAdminControllerGetByIdResponses];

export type BeverageAdminControllerUpdateData = {
    body: UpdateBeverageDto;
    path: {
        /**
         * Beverage ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverages/{id}';
};

export type BeverageAdminControllerUpdateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageAdminControllerUpdateResponses = {
    /**
     * Beverage updated
     */
    200: Beverage;
};

export type BeverageAdminControllerUpdateResponse = BeverageAdminControllerUpdateResponses[keyof BeverageAdminControllerUpdateResponses];

export type BeverageWebControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/beverages';
};

export type BeverageWebControllerGetAllResponses = {
    /**
     * List of beverages
     */
    200: Array<Beverage>;
};

export type BeverageWebControllerGetAllResponse = BeverageWebControllerGetAllResponses[keyof BeverageWebControllerGetAllResponses];

export type BeverageWebControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Beverage ID
         */
        id: string;
    };
    query?: never;
    url: '/api/beverages/{id}';
};

export type BeverageWebControllerGetByIdErrors = {
    /**
     * Beverage not found
     */
    404: unknown;
};

export type BeverageWebControllerGetByIdResponses = {
    /**
     * Beverage found
     */
    200: Beverage;
};

export type BeverageWebControllerGetByIdResponse = BeverageWebControllerGetByIdResponses[keyof BeverageWebControllerGetByIdResponses];

export type ReviewAdminControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/reviews';
};

export type ReviewAdminControllerGetAllResponses = {
    /**
     * List of reviews
     */
    200: Array<Review>;
};

export type ReviewAdminControllerGetAllResponse = ReviewAdminControllerGetAllResponses[keyof ReviewAdminControllerGetAllResponses];

export type ReviewAdminControllerCreateData = {
    body: CreateReviewDto;
    path?: never;
    query?: never;
    url: '/api/admin/reviews';
};

export type ReviewAdminControllerCreateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type ReviewAdminControllerCreateResponses = {
    /**
     * Review created
     */
    201: Review;
};

export type ReviewAdminControllerCreateResponse = ReviewAdminControllerCreateResponses[keyof ReviewAdminControllerCreateResponses];

export type ReviewAdminControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Review ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{id}';
};

export type ReviewAdminControllerRemoveErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type ReviewAdminControllerRemoveResponses = {
    /**
     * Review deleted
     */
    200: {
        deleted?: boolean;
    };
};

export type ReviewAdminControllerRemoveResponse = ReviewAdminControllerRemoveResponses[keyof ReviewAdminControllerRemoveResponses];

export type ReviewAdminControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Review ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{id}';
};

export type ReviewAdminControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type ReviewAdminControllerGetByIdResponses = {
    /**
     * Review found
     */
    200: Review;
};

export type ReviewAdminControllerGetByIdResponse = ReviewAdminControllerGetByIdResponses[keyof ReviewAdminControllerGetByIdResponses];

export type ReviewAdminControllerUpdateData = {
    body: UpdateReviewDto;
    path: {
        /**
         * Review ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{id}';
};

export type ReviewAdminControllerUpdateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type ReviewAdminControllerUpdateResponses = {
    /**
     * Review updated
     */
    200: Review;
};

export type ReviewAdminControllerUpdateResponse = ReviewAdminControllerUpdateResponses[keyof ReviewAdminControllerUpdateResponses];

export type ReviewWebControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type ReviewWebControllerGetAllResponses = {
    /**
     * List of reviews
     */
    200: Array<Review>;
};

export type ReviewWebControllerGetAllResponse = ReviewWebControllerGetAllResponses[keyof ReviewWebControllerGetAllResponses];

export type ReviewWebControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Review ID
         */
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}';
};

export type ReviewWebControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type ReviewWebControllerGetByIdResponses = {
    /**
     * Review found
     */
    200: Review;
};

export type ReviewWebControllerGetByIdResponse = ReviewWebControllerGetByIdResponses[keyof ReviewWebControllerGetByIdResponses];

export type BeverageCategoryAdminControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/beverage-categories';
};

export type BeverageCategoryAdminControllerGetAllResponses = {
    /**
     * List of categories
     */
    200: Array<BeverageCategory>;
};

export type BeverageCategoryAdminControllerGetAllResponse = BeverageCategoryAdminControllerGetAllResponses[keyof BeverageCategoryAdminControllerGetAllResponses];

export type BeverageCategoryAdminControllerCreateData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/api/admin/beverage-categories';
};

export type BeverageCategoryAdminControllerCreateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type BeverageCategoryAdminControllerCreateResponses = {
    /**
     * Category created
     */
    201: BeverageCategory;
};

export type BeverageCategoryAdminControllerCreateResponse = BeverageCategoryAdminControllerCreateResponses[keyof BeverageCategoryAdminControllerCreateResponses];

export type BeverageCategoryAdminControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Category ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-categories/{id}';
};

export type BeverageCategoryAdminControllerRemoveErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Category has types or brands
     */
    409: unknown;
};

export type BeverageCategoryAdminControllerRemoveResponses = {
    /**
     * Category deleted
     */
    200: {
        deleted?: boolean;
    };
};

export type BeverageCategoryAdminControllerRemoveResponse = BeverageCategoryAdminControllerRemoveResponses[keyof BeverageCategoryAdminControllerRemoveResponses];

export type BeverageCategoryAdminControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Category ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-categories/{id}';
};

export type BeverageCategoryAdminControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageCategoryAdminControllerGetByIdResponses = {
    /**
     * Category found
     */
    200: BeverageCategory;
};

export type BeverageCategoryAdminControllerGetByIdResponse = BeverageCategoryAdminControllerGetByIdResponses[keyof BeverageCategoryAdminControllerGetByIdResponses];

export type BeverageCategoryAdminControllerUpdateData = {
    body: UpdateCategoryDto;
    path: {
        /**
         * Category ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-categories/{id}';
};

export type BeverageCategoryAdminControllerUpdateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageCategoryAdminControllerUpdateResponses = {
    /**
     * Category updated
     */
    200: BeverageCategory;
};

export type BeverageCategoryAdminControllerUpdateResponse = BeverageCategoryAdminControllerUpdateResponses[keyof BeverageCategoryAdminControllerUpdateResponses];

export type BeverageCategoryWebControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/beverage-categories';
};

export type BeverageCategoryWebControllerGetAllResponses = {
    /**
     * List of categories
     */
    200: Array<BeverageCategory>;
};

export type BeverageCategoryWebControllerGetAllResponse = BeverageCategoryWebControllerGetAllResponses[keyof BeverageCategoryWebControllerGetAllResponses];

export type BeverageCategoryWebControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Category ID
         */
        id: string;
    };
    query?: never;
    url: '/api/beverage-categories/{id}';
};

export type BeverageCategoryWebControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageCategoryWebControllerGetByIdResponses = {
    /**
     * Category found
     */
    200: BeverageCategory;
};

export type BeverageCategoryWebControllerGetByIdResponse = BeverageCategoryWebControllerGetByIdResponses[keyof BeverageCategoryWebControllerGetByIdResponses];

export type BeverageTypeAdminControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/beverage-types';
};

export type BeverageTypeAdminControllerGetAllResponses = {
    /**
     * List of types
     */
    200: Array<BeverageType>;
};

export type BeverageTypeAdminControllerGetAllResponse = BeverageTypeAdminControllerGetAllResponses[keyof BeverageTypeAdminControllerGetAllResponses];

export type BeverageTypeAdminControllerCreateData = {
    body: CreateBeverageTypeDto;
    path?: never;
    query?: never;
    url: '/api/admin/beverage-types';
};

export type BeverageTypeAdminControllerCreateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type BeverageTypeAdminControllerCreateResponses = {
    /**
     * Type created
     */
    201: BeverageType;
};

export type BeverageTypeAdminControllerCreateResponse = BeverageTypeAdminControllerCreateResponses[keyof BeverageTypeAdminControllerCreateResponses];

export type BeverageTypeAdminControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Beverage type ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-types/{id}';
};

export type BeverageTypeAdminControllerRemoveErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Type has beverages
     */
    409: unknown;
};

export type BeverageTypeAdminControllerRemoveResponses = {
    /**
     * Type deleted
     */
    200: {
        deleted?: boolean;
    };
};

export type BeverageTypeAdminControllerRemoveResponse = BeverageTypeAdminControllerRemoveResponses[keyof BeverageTypeAdminControllerRemoveResponses];

export type BeverageTypeAdminControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Beverage type ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-types/{id}';
};

export type BeverageTypeAdminControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageTypeAdminControllerGetByIdResponses = {
    /**
     * Type found
     */
    200: BeverageType;
};

export type BeverageTypeAdminControllerGetByIdResponse = BeverageTypeAdminControllerGetByIdResponses[keyof BeverageTypeAdminControllerGetByIdResponses];

export type BeverageTypeAdminControllerUpdateData = {
    body: UpdateBeverageTypeDto;
    path: {
        /**
         * Beverage type ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-types/{id}';
};

export type BeverageTypeAdminControllerUpdateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageTypeAdminControllerUpdateResponses = {
    /**
     * Type updated
     */
    200: BeverageType;
};

export type BeverageTypeAdminControllerUpdateResponse = BeverageTypeAdminControllerUpdateResponses[keyof BeverageTypeAdminControllerUpdateResponses];

export type BeverageTypeWebControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/beverage-types';
};

export type BeverageTypeWebControllerGetAllResponses = {
    /**
     * List of types
     */
    200: Array<BeverageType>;
};

export type BeverageTypeWebControllerGetAllResponse = BeverageTypeWebControllerGetAllResponses[keyof BeverageTypeWebControllerGetAllResponses];

export type BeverageTypeWebControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Beverage type ID
         */
        id: string;
    };
    query?: never;
    url: '/api/beverage-types/{id}';
};

export type BeverageTypeWebControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageTypeWebControllerGetByIdResponses = {
    /**
     * Type found
     */
    200: BeverageType;
};

export type BeverageTypeWebControllerGetByIdResponse = BeverageTypeWebControllerGetByIdResponses[keyof BeverageTypeWebControllerGetByIdResponses];

export type BrandAdminControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/brands';
};

export type BrandAdminControllerGetAllResponses = {
    /**
     * List of brands
     */
    200: Array<Brand>;
};

export type BrandAdminControllerGetAllResponse = BrandAdminControllerGetAllResponses[keyof BrandAdminControllerGetAllResponses];

export type BrandAdminControllerCreateData = {
    body: CreateBrandDto;
    path?: never;
    query?: never;
    url: '/api/admin/brands';
};

export type BrandAdminControllerCreateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type BrandAdminControllerCreateResponses = {
    /**
     * Brand created
     */
    201: Brand;
};

export type BrandAdminControllerCreateResponse = BrandAdminControllerCreateResponses[keyof BrandAdminControllerCreateResponses];

export type BrandAdminControllerGetByCategoryData = {
    body?: never;
    path: {
        /**
         * Beverage category ID
         */
        categoryId: string;
    };
    query?: never;
    url: '/api/admin/brands/category/{categoryId}';
};

export type BrandAdminControllerGetByCategoryResponses = {
    /**
     * List of brands
     */
    200: Array<Brand>;
};

export type BrandAdminControllerGetByCategoryResponse = BrandAdminControllerGetByCategoryResponses[keyof BrandAdminControllerGetByCategoryResponses];

export type BrandAdminControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Brand ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/brands/{id}';
};

export type BrandAdminControllerRemoveErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Brand has beverages
     */
    409: unknown;
};

export type BrandAdminControllerRemoveResponses = {
    /**
     * Brand deleted
     */
    200: {
        deleted?: boolean;
    };
};

export type BrandAdminControllerRemoveResponse = BrandAdminControllerRemoveResponses[keyof BrandAdminControllerRemoveResponses];

export type BrandAdminControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Brand ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/brands/{id}';
};

export type BrandAdminControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type BrandAdminControllerGetByIdResponses = {
    /**
     * Brand found
     */
    200: Brand;
};

export type BrandAdminControllerGetByIdResponse = BrandAdminControllerGetByIdResponses[keyof BrandAdminControllerGetByIdResponses];

export type BrandAdminControllerUpdateData = {
    body: UpdateBrandDto;
    path: {
        /**
         * Brand ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/brands/{id}';
};

export type BrandAdminControllerUpdateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type BrandAdminControllerUpdateResponses = {
    /**
     * Brand updated
     */
    200: Brand;
};

export type BrandAdminControllerUpdateResponse = BrandAdminControllerUpdateResponses[keyof BrandAdminControllerUpdateResponses];

export type BrandWebControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/brands';
};

export type BrandWebControllerGetAllResponses = {
    /**
     * List of brands
     */
    200: Array<Brand>;
};

export type BrandWebControllerGetAllResponse = BrandWebControllerGetAllResponses[keyof BrandWebControllerGetAllResponses];

export type BrandWebControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Brand ID
         */
        id: string;
    };
    query?: never;
    url: '/api/brands/{id}';
};

export type BrandWebControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type BrandWebControllerGetByIdResponses = {
    /**
     * Brand found
     */
    200: Brand;
};

export type BrandWebControllerGetByIdResponse = BrandWebControllerGetByIdResponses[keyof BrandWebControllerGetByIdResponses];

export type AttributeDefinitionAdminControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/attributes';
};

export type AttributeDefinitionAdminControllerFindAllResponses = {
    /**
     * List of attribute definitions
     */
    200: Array<AttributeDefinition>;
};

export type AttributeDefinitionAdminControllerFindAllResponse = AttributeDefinitionAdminControllerFindAllResponses[keyof AttributeDefinitionAdminControllerFindAllResponses];

export type AttributeDefinitionAdminControllerCreateData = {
    body: CreateAttributeDefinitionDto;
    path?: never;
    query?: never;
    url: '/api/admin/attributes';
};

export type AttributeDefinitionAdminControllerCreateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type AttributeDefinitionAdminControllerCreateResponses = {
    /**
     * Attribute definition created
     */
    201: AttributeDefinition;
};

export type AttributeDefinitionAdminControllerCreateResponse = AttributeDefinitionAdminControllerCreateResponses[keyof AttributeDefinitionAdminControllerCreateResponses];

export type AttributeDefinitionAdminControllerFindByCategoryData = {
    body?: never;
    path: {
        /**
         * Beverage category ID
         */
        categoryId: string;
    };
    query?: never;
    url: '/api/admin/attributes/category/{categoryId}';
};

export type AttributeDefinitionAdminControllerFindByCategoryResponses = {
    /**
     * List of attribute definitions
     */
    200: Array<AttributeDefinition>;
};

export type AttributeDefinitionAdminControllerFindByCategoryResponse = AttributeDefinitionAdminControllerFindByCategoryResponses[keyof AttributeDefinitionAdminControllerFindByCategoryResponses];

export type AttributeDefinitionAdminControllerFindByTypeData = {
    body?: never;
    path: {
        /**
         * Beverage type ID
         */
        beverageTypeId: string;
    };
    query?: never;
    url: '/api/admin/attributes/type/{beverageTypeId}';
};

export type AttributeDefinitionAdminControllerFindByTypeResponses = {
    /**
     * List of attribute definitions
     */
    200: Array<AttributeDefinition>;
};

export type AttributeDefinitionAdminControllerFindByTypeResponse = AttributeDefinitionAdminControllerFindByTypeResponses[keyof AttributeDefinitionAdminControllerFindByTypeResponses];

export type AttributeDefinitionAdminControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Attribute definition ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/attributes/{id}';
};

export type AttributeDefinitionAdminControllerRemoveErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type AttributeDefinitionAdminControllerRemoveResponses = {
    /**
     * Attribute definition deleted
     */
    200: {
        deleted?: boolean;
    };
};

export type AttributeDefinitionAdminControllerRemoveResponse = AttributeDefinitionAdminControllerRemoveResponses[keyof AttributeDefinitionAdminControllerRemoveResponses];

export type AttributeDefinitionAdminControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Attribute definition ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/attributes/{id}';
};

export type AttributeDefinitionAdminControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type AttributeDefinitionAdminControllerGetByIdResponses = {
    /**
     * Attribute definition found
     */
    200: AttributeDefinition;
};

export type AttributeDefinitionAdminControllerGetByIdResponse = AttributeDefinitionAdminControllerGetByIdResponses[keyof AttributeDefinitionAdminControllerGetByIdResponses];

export type AttributeDefinitionAdminControllerUpdateData = {
    body: UpdateAttributeDefinitionDto;
    path: {
        /**
         * Attribute definition ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/attributes/{id}';
};

export type AttributeDefinitionAdminControllerUpdateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type AttributeDefinitionAdminControllerUpdateResponses = {
    /**
     * Attribute definition updated
     */
    200: AttributeDefinition;
};

export type AttributeDefinitionAdminControllerUpdateResponse = AttributeDefinitionAdminControllerUpdateResponses[keyof AttributeDefinitionAdminControllerUpdateResponses];

export type AttributeDefinitionWebControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/attributes';
};

export type AttributeDefinitionWebControllerFindAllResponses = {
    /**
     * List of attribute definitions
     */
    200: Array<AttributeDefinition>;
};

export type AttributeDefinitionWebControllerFindAllResponse = AttributeDefinitionWebControllerFindAllResponses[keyof AttributeDefinitionWebControllerFindAllResponses];

export type AttributeDefinitionWebControllerFindByCategoryData = {
    body?: never;
    path: {
        /**
         * Beverage category ID
         */
        categoryId: string;
    };
    query?: never;
    url: '/api/attributes/category/{categoryId}';
};

export type AttributeDefinitionWebControllerFindByCategoryResponses = {
    /**
     * List of attribute definitions
     */
    200: Array<AttributeDefinition>;
};

export type AttributeDefinitionWebControllerFindByCategoryResponse = AttributeDefinitionWebControllerFindByCategoryResponses[keyof AttributeDefinitionWebControllerFindByCategoryResponses];

export type AttributeDefinitionWebControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Attribute definition ID
         */
        id: string;
    };
    query?: never;
    url: '/api/attributes/{id}';
};

export type AttributeDefinitionWebControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type AttributeDefinitionWebControllerGetByIdResponses = {
    /**
     * Attribute definition found
     */
    200: AttributeDefinition;
};

export type AttributeDefinitionWebControllerGetByIdResponse = AttributeDefinitionWebControllerGetByIdResponses[keyof AttributeDefinitionWebControllerGetByIdResponses];

export type BeverageAttributeValueAdminControllerCreateData = {
    body: CreateBeverageAttributeValueDto;
    path?: never;
    query?: never;
    url: '/api/admin/beverage-attributes';
};

export type BeverageAttributeValueAdminControllerCreateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type BeverageAttributeValueAdminControllerCreateResponses = {
    /**
     * Attribute value created
     */
    201: BeverageAttributeValue;
};

export type BeverageAttributeValueAdminControllerCreateResponse = BeverageAttributeValueAdminControllerCreateResponses[keyof BeverageAttributeValueAdminControllerCreateResponses];

export type BeverageAttributeValueAdminControllerFindAllForBeverageData = {
    body?: never;
    path: {
        /**
         * Beverage ID
         */
        beverageId: string;
    };
    query?: never;
    url: '/api/admin/beverage-attributes/beverage/{beverageId}';
};

export type BeverageAttributeValueAdminControllerFindAllForBeverageResponses = {
    /**
     * List of attribute values
     */
    200: Array<BeverageAttributeValue>;
};

export type BeverageAttributeValueAdminControllerFindAllForBeverageResponse = BeverageAttributeValueAdminControllerFindAllForBeverageResponses[keyof BeverageAttributeValueAdminControllerFindAllForBeverageResponses];

export type BeverageAttributeValueAdminControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Attribute value ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-attributes/{id}';
};

export type BeverageAttributeValueAdminControllerRemoveErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageAttributeValueAdminControllerRemoveResponses = {
    /**
     * Attribute value deleted
     */
    200: {
        deleted?: boolean;
    };
};

export type BeverageAttributeValueAdminControllerRemoveResponse = BeverageAttributeValueAdminControllerRemoveResponses[keyof BeverageAttributeValueAdminControllerRemoveResponses];

export type BeverageAttributeValueAdminControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Attribute value ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-attributes/{id}';
};

export type BeverageAttributeValueAdminControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageAttributeValueAdminControllerGetByIdResponses = {
    /**
     * Attribute value found
     */
    200: BeverageAttributeValue;
};

export type BeverageAttributeValueAdminControllerGetByIdResponse = BeverageAttributeValueAdminControllerGetByIdResponses[keyof BeverageAttributeValueAdminControllerGetByIdResponses];

export type BeverageAttributeValueAdminControllerUpdateData = {
    body: UpdateBeverageAttributeValueDto;
    path: {
        /**
         * Attribute value ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-attributes/{id}';
};

export type BeverageAttributeValueAdminControllerUpdateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type BeverageAttributeValueAdminControllerUpdateResponses = {
    /**
     * Attribute value updated
     */
    200: BeverageAttributeValue;
};

export type BeverageAttributeValueAdminControllerUpdateResponse = BeverageAttributeValueAdminControllerUpdateResponses[keyof BeverageAttributeValueAdminControllerUpdateResponses];

export type BeverageAttributeValueWebControllerFindAllForBeverageData = {
    body?: never;
    path: {
        /**
         * Beverage ID
         */
        beverageId: string;
    };
    query?: never;
    url: '/api/beverage-attributes/beverage/{beverageId}';
};

export type BeverageAttributeValueWebControllerFindAllForBeverageResponses = {
    /**
     * List of attribute values
     */
    200: Array<BeverageAttributeValue>;
};

export type BeverageAttributeValueWebControllerFindAllForBeverageResponse = BeverageAttributeValueWebControllerFindAllForBeverageResponses[keyof BeverageAttributeValueWebControllerFindAllForBeverageResponses];

export type QuestionAdminControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/questions';
};

export type QuestionAdminControllerFindAllResponses = {
    /**
     * List of questions
     */
    200: Array<Question>;
};

export type QuestionAdminControllerFindAllResponse = QuestionAdminControllerFindAllResponses[keyof QuestionAdminControllerFindAllResponses];

export type QuestionAdminControllerCreateData = {
    body: CreateQuestionDto;
    path?: never;
    query?: never;
    url: '/api/admin/questions';
};

export type QuestionAdminControllerCreateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type QuestionAdminControllerCreateResponses = {
    /**
     * Question created
     */
    201: Question;
};

export type QuestionAdminControllerCreateResponse = QuestionAdminControllerCreateResponses[keyof QuestionAdminControllerCreateResponses];

export type QuestionAdminControllerFindByCategoryData = {
    body?: never;
    path: {
        /**
         * Beverage category ID
         */
        categoryId: string;
    };
    query?: never;
    url: '/api/admin/questions/category/{categoryId}';
};

export type QuestionAdminControllerFindByCategoryResponses = {
    /**
     * List of questions
     */
    200: Array<Question>;
};

export type QuestionAdminControllerFindByCategoryResponse = QuestionAdminControllerFindByCategoryResponses[keyof QuestionAdminControllerFindByCategoryResponses];

export type QuestionAdminControllerFindByTypeData = {
    body?: never;
    path: {
        /**
         * Beverage type ID
         */
        typeId: string;
    };
    query?: never;
    url: '/api/admin/questions/type/{typeId}';
};

export type QuestionAdminControllerFindByTypeResponses = {
    /**
     * List of questions
     */
    200: Array<Question>;
};

export type QuestionAdminControllerFindByTypeResponse = QuestionAdminControllerFindByTypeResponses[keyof QuestionAdminControllerFindByTypeResponses];

export type QuestionAdminControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Question ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/questions/{id}';
};

export type QuestionAdminControllerRemoveErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type QuestionAdminControllerRemoveResponses = {
    /**
     * Question deleted
     */
    200: {
        deleted?: boolean;
    };
};

export type QuestionAdminControllerRemoveResponse = QuestionAdminControllerRemoveResponses[keyof QuestionAdminControllerRemoveResponses];

export type QuestionAdminControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Question ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/questions/{id}';
};

export type QuestionAdminControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type QuestionAdminControllerGetByIdResponses = {
    /**
     * Question found
     */
    200: Question;
};

export type QuestionAdminControllerGetByIdResponse = QuestionAdminControllerGetByIdResponses[keyof QuestionAdminControllerGetByIdResponses];

export type QuestionAdminControllerUpdateData = {
    body: UpdateQuestionDto;
    path: {
        /**
         * Question ID
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/questions/{id}';
};

export type QuestionAdminControllerUpdateErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type QuestionAdminControllerUpdateResponses = {
    /**
     * Question updated
     */
    200: Question;
};

export type QuestionAdminControllerUpdateResponse = QuestionAdminControllerUpdateResponses[keyof QuestionAdminControllerUpdateResponses];

export type QuestionWebControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/questions';
};

export type QuestionWebControllerFindAllResponses = {
    /**
     * List of questions
     */
    200: Array<Question>;
};

export type QuestionWebControllerFindAllResponse = QuestionWebControllerFindAllResponses[keyof QuestionWebControllerFindAllResponses];

export type QuestionWebControllerFindByCategoryData = {
    body?: never;
    path: {
        /**
         * Beverage category ID
         */
        categoryId: string;
    };
    query?: never;
    url: '/api/questions/category/{categoryId}';
};

export type QuestionWebControllerFindByCategoryResponses = {
    /**
     * List of questions
     */
    200: Array<Question>;
};

export type QuestionWebControllerFindByCategoryResponse = QuestionWebControllerFindByCategoryResponses[keyof QuestionWebControllerFindByCategoryResponses];

export type QuestionWebControllerFindByTypeData = {
    body?: never;
    path: {
        /**
         * Beverage type ID
         */
        typeId: string;
    };
    query?: never;
    url: '/api/questions/type/{typeId}';
};

export type QuestionWebControllerFindByTypeResponses = {
    /**
     * List of questions
     */
    200: Array<Question>;
};

export type QuestionWebControllerFindByTypeResponse = QuestionWebControllerFindByTypeResponses[keyof QuestionWebControllerFindByTypeResponses];

export type QuestionWebControllerGetByIdData = {
    body?: never;
    path: {
        /**
         * Question ID
         */
        id: string;
    };
    query?: never;
    url: '/api/questions/{id}';
};

export type QuestionWebControllerGetByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type QuestionWebControllerGetByIdResponses = {
    /**
     * Question found
     */
    200: Question;
};

export type QuestionWebControllerGetByIdResponse = QuestionWebControllerGetByIdResponses[keyof QuestionWebControllerGetByIdResponses];
