// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type BeverageCategory = {
    id?: string;
    name?: string;
    description?: string | null;
};

export type CreateCategoryDto = {
    name: string;
    description?: string;
    images?: Array<CreateImageDto>;
};

export type CreateImageDto = {
    url: string;
    type: 'THUMBNAIL' | 'LARGE' | 'PROFILE' | 'ICON';
    width?: number;
    height?: number;
};

export type BeverageType = {
    id?: string;
    categoryId?: string;
    name?: string;
    description?: string | null;
    active?: boolean;
};

export type CreateBeverageTypeDto = {
    name: string;
    categoryId: string;
    description?: string;
    active?: boolean;
};

export type BeverageImage = {
    id?: string;
    url?: string;
    type?: 'THUMBNAIL' | 'LARGE' | 'PROFILE' | 'ICON';
    width?: number | null;
    height?: number | null;
};

export type Beverage = {
    id?: string;
    beverageTypeId?: string;
    brand?: string;
    name?: string;
    country?: string;
    metadata?: unknown;
    averageRating?: number;
    reviewCount?: number;
    images?: Array<BeverageImage>;
};

export type CreateBeverageDto = {
    beverageTypeId: string;
    brand: string;
    name: string;
    country?: string;
    metadata?: unknown;
    images?: Array<CreateImageDto>;
};

export type AttributeDefinition = {
    id?: string;
    categoryId?: string;
    typeId?: string | null;
    attributeKey?: string;
    displayName?: string;
    dataType?: string;
    filterable?: boolean;
    required?: boolean;
};

export type CreateAttributeDefinitionDto = {
    categoryId: string;
    typeId?: string;
    attributeKey: string;
    displayName: string;
    dataType: string;
    filterable?: boolean;
    required?: boolean;
};

export type ReviewAnswerQuestion = {
    id?: string;
    questionText?: string;
    answerType?: string;
};

export type ReviewAnswerWithQuestion = {
    id?: string;
    reviewId?: string;
    questionId?: string;
    answer?: string;
    question?: ReviewAnswerQuestion;
};

export type Review = {
    id?: string;
    userId?: string;
    beverageId?: string;
    rating?: number;
    title?: string | null;
    description?: string | null;
    answers?: Array<ReviewAnswerWithQuestion>;
};

export type Question = {
    id?: string;
    categoryId?: string;
    typeId?: string | null;
    questionText?: string;
    answerType?: string;
    options?: unknown;
    sortOrder?: number | null;
    required?: boolean;
};

export type CreateQuestionDto = {
    categoryId: string;
    typeId?: string;
    questionText: string;
    answerType: string;
    options?: unknown;
    sortOrder?: number;
    required?: boolean;
};

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/beverage-categories';
};

export type GetAllCategoriesResponses = {
    200: Array<BeverageCategory>;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type CreateCategoryData = {
    body?: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/api/admin/beverage-categories';
};

export type CreateCategoryResponses = {
    201: BeverageCategory;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type GetCategoryByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-categories/{id}';
};

export type GetCategoryByIdResponses = {
    200: BeverageCategory;
};

export type GetCategoryByIdResponse = GetCategoryByIdResponses[keyof GetCategoryByIdResponses];

export type GetAllTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/beverage-types';
};

export type GetAllTypesResponses = {
    200: Array<BeverageType>;
};

export type GetAllTypesResponse = GetAllTypesResponses[keyof GetAllTypesResponses];

export type CreateTypeData = {
    body?: CreateBeverageTypeDto;
    path?: never;
    query?: never;
    url: '/api/admin/beverage-types';
};

export type CreateTypeResponses = {
    201: BeverageType;
};

export type CreateTypeResponse = CreateTypeResponses[keyof CreateTypeResponses];

export type GetTypeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/beverage-types/{id}';
};

export type GetTypeByIdResponses = {
    200: BeverageType;
};

export type GetTypeByIdResponse = GetTypeByIdResponses[keyof GetTypeByIdResponses];

export type GetAllBeveragesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/beverages';
};

export type GetAllBeveragesResponses = {
    200: Array<Beverage>;
};

export type GetAllBeveragesResponse = GetAllBeveragesResponses[keyof GetAllBeveragesResponses];

export type CreateBeverageData = {
    body?: CreateBeverageDto;
    path?: never;
    query?: never;
    url: '/api/admin/beverages';
};

export type CreateBeverageResponses = {
    201: Beverage;
};

export type CreateBeverageResponse = CreateBeverageResponses[keyof CreateBeverageResponses];

export type GetBeverageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/beverages/{id}';
};

export type GetBeverageByIdErrors = {
    /**
     * Beverage not found
     */
    404: unknown;
};

export type GetBeverageByIdResponses = {
    200: Beverage;
};

export type GetBeverageByIdResponse = GetBeverageByIdResponses[keyof GetBeverageByIdResponses];

export type FindAllAttributesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/attributes';
};

export type FindAllAttributesResponses = {
    200: Array<AttributeDefinition>;
};

export type FindAllAttributesResponse = FindAllAttributesResponses[keyof FindAllAttributesResponses];

export type CreateAttributeData = {
    body?: CreateAttributeDefinitionDto;
    path?: never;
    query?: never;
    url: '/api/admin/attributes';
};

export type CreateAttributeResponses = {
    201: AttributeDefinition;
};

export type CreateAttributeResponse = CreateAttributeResponses[keyof CreateAttributeResponses];

export type FindAttributesByCategoryData = {
    body?: never;
    path: {
        categoryId: string;
    };
    query?: never;
    url: '/api/admin/attributes/category/{categoryId}';
};

export type FindAttributesByCategoryResponses = {
    200: Array<AttributeDefinition>;
};

export type FindAttributesByCategoryResponse = FindAttributesByCategoryResponses[keyof FindAttributesByCategoryResponses];

export type GetAttributeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/attributes/{id}';
};

export type GetAttributeByIdErrors = {
    /**
     * Attribute definition not found
     */
    404: unknown;
};

export type GetAttributeByIdResponses = {
    200: AttributeDefinition;
};

export type GetAttributeByIdResponse = GetAttributeByIdResponses[keyof GetAttributeByIdResponses];

export type GetAllReviewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/reviews';
};

export type GetAllReviewsResponses = {
    200: Array<Review>;
};

export type GetAllReviewsResponse = GetAllReviewsResponses[keyof GetAllReviewsResponses];

export type GetReviewByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/reviews/{id}';
};

export type GetReviewByIdErrors = {
    /**
     * Review not found
     */
    404: unknown;
};

export type GetReviewByIdResponses = {
    200: Review;
};

export type GetReviewByIdResponse = GetReviewByIdResponses[keyof GetReviewByIdResponses];

export type FindAllQuestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/questions';
};

export type FindAllQuestionsResponses = {
    200: Array<Question>;
};

export type FindAllQuestionsResponse = FindAllQuestionsResponses[keyof FindAllQuestionsResponses];

export type CreateQuestionData = {
    body?: CreateQuestionDto;
    path?: never;
    query?: never;
    url: '/api/admin/questions';
};

export type CreateQuestionResponses = {
    201: Question;
};

export type CreateQuestionResponse = CreateQuestionResponses[keyof CreateQuestionResponses];

export type FindQuestionsByCategoryData = {
    body?: never;
    path: {
        categoryId: string;
    };
    query?: never;
    url: '/api/admin/questions/category/{categoryId}';
};

export type FindQuestionsByCategoryResponses = {
    200: Array<Question>;
};

export type FindQuestionsByCategoryResponse = FindQuestionsByCategoryResponses[keyof FindQuestionsByCategoryResponses];

export type FindQuestionsByTypeData = {
    body?: never;
    path: {
        typeId: string;
    };
    query?: never;
    url: '/api/admin/questions/type/{typeId}';
};

export type FindQuestionsByTypeResponses = {
    200: Array<Question>;
};

export type FindQuestionsByTypeResponse = FindQuestionsByTypeResponses[keyof FindQuestionsByTypeResponses];

export type DeleteQuestionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/questions/{id}';
};

export type DeleteQuestionErrors = {
    /**
     * Question not found
     */
    404: unknown;
};

export type DeleteQuestionResponses = {
    /**
     * Question deleted, sortOrder compacted
     */
    200: unknown;
};

export type GetQuestionByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/questions/{id}';
};

export type GetQuestionByIdErrors = {
    /**
     * Question not found
     */
    404: unknown;
};

export type GetQuestionByIdResponses = {
    200: Question;
};

export type GetQuestionByIdResponse = GetQuestionByIdResponses[keyof GetQuestionByIdResponses];
